version: "3.8"
services:
  backend:
    image: sathirahguruge/aarya_backend:1
    build: ./backend
    environment:
      - AARYA_DB_URL=mongodb://database
    ports:
      - 3001:3001
  database:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - aarya:/data/db
volumes:
  aarya:
