on:
  push:
    branches:
      - "ci-cd-test"

env:
  DOCKER_HUB_USERNAME: ${{secrets.DOCKER_HUB_USERNAME}}
  DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
  AARYA_DB_NAME: ${{secrets.AARYA_DB_NAME}}
  AARYA_JWT_KEY: ${{secrets.AARYA_JWT_KEY}}

jobs:
  test:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      -
       name: Checkout repository
       uses: actions/checkout@v3

      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{env.DOCKER_HUB_USERNAME}}
          password: ${{env.DOCKERHUB_TOKEN}}        
        
      - name: Docker Build
        run: docker-compose build --build-arg AARYA_JWT_KEY=${{env.DOCKER_HUB_USERNAME}} --build-arg AARYA_DB_NAME=${{env.AARYA_DB_NAME}}
        
      - name: Docker Push
        run: docker compose push
